export const SERVER_HEADER = {
  ADD_CLIENT: 0,
  SET_OUR_ENTITY: 1,
  UPDATE_ENTITY: 2,
  CONFIG: 3,
  REMOVE_ENTITY: 4,
  ADD_ENTITY: 5,
  SWAP_ITEM: 6,
  ACTION: 7,
  HIT_BOUNCE_EFFECT: 8,
  DIED: 9,
  INVENTORY: 10,
  UPDATE_HEALTH: 11,
  LEADERBOARD: 12,
  HEALTH: 13,
  CHAT: 14,
}

export const CLIENT_HEADER = {
  REQUEST_RESPAWN: 0,
  INPUT: 1,
  MOUSE_DOWN: 2,
  MOUSE_UP: 3,
  INVENTORY: 4,
  CHAT: 5,
}